project_id = "zzwujetawkfqhxkwakjr"

[auth]
site_url = "https://wiseauto-app.vercel.app"
additional_redirect_urls = [
  "https://wiseauto-app.vercel.app/dashboard",
  "https://wiseauto-app.vercel.app/reset-password",
  "http://localhost:8080/dashboard",
  "http://localhost:8080/reset-password"
]

[auth.email]
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.cnpj-lookup]
verify_jwt = false
