// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzwujetawkfqhxkwakjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6d3VqZXRhd2tmcWh4a3dha2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNDgzNDAsImV4cCI6MjA3ODkyNDM0MH0.GcsNHBpR8ykmmo61BlNl0yk0XvJ6ej16WI1WeJu7otY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});